### ISSUE TITLE
带边框的仿微信消息框实现

### ISSUE THREAD

**Issue by xiaokk06** [xiaokk06/pseudo-classes-and-elements#1]
### 消息框实现
&ensp;&ensp;相信大家都知道怎么去生成一个类似微信的消息框，类似微信的消息框。在这里稍微说一下原理，其实就是利用伪元素在矩形对应的位置添加一个三角形即可，但是如果三角形需要一个边框，这样如何实现呢？

### 解决方案
&ensp;&ensp;其实原理很简单，既然一个是一个三角形，那么我添加两个，让下面的三角形被上面的覆盖只留下一个边框的效果不久可以实现了吗？具体实现如下：

```html
<div class="test-div"></div>
```

```css
.test-div {
        position: relative;
        /*日常相对定位*/
        width: 150px;
        height: 36px;
        border: black 1px solid;
        border-radius: 5px;
        background: rgba(245, 245, 245, 1);
    }
    
    .test-div:before,
    .test-div:after {
        content: "";
        display: block;
        position: absolute;
        /*日常绝对定位*/
        top: 8px;
        width: 0;
        height: 0;
        border: 6px transparent solid;
    }
    /**
     * 通过border的定位来实现左边小三角的边框效果
     * ::after的left值要比::before更小 同时具有更低的z-index
     * 因此会被::before覆盖只显示出边框效果
     * @type {[type]}
     */
    
    .test-div:before {
        left: -11px;
        border-right-color: rgba(245, 245, 245, 1);
        z-index: 1;
    }
    
    .test-div:after {
        left: -12px;
        border-right-color: rgba(0, 0, 0, 1);
        z-index: 0;
    }
```

demo地址：http://codepen.io/xiaokk06/pen/PGJOZK

### 结语
&ensp;&ensp;个人觉得这种方式实现有点hack的意思，但是不失为一种解决方法，另外如果不想使用伪元素可以尝试css3的滤镜效果。实现了这个，是不是对微信和qq的消息气泡实现有些思路了呢？
