### ISSUE TITLE
鼠标浮动放大效果实现

### ISSUE THREAD

**Issue by xiaokk06** [xiaokk06/pseudo-classes-and-elements#2]
### 鼠标悬浮放大效果
&ensp;&ensp;实现一个鼠标悬浮在元素上时元素放大的效果可以利用scale方法来实现，具体实现如下；

```html
<div class="box"></div>
<div class="box"></div>
<div class="box"></div>
```

```css
.box {
  position: relative;
  display: inline-block;
  width: 100px;
  height: 100px;
  margin: 20px;
  background-color: #fff;
  border-radius: 5px;
  box-shadow: 0 1px 2px rgba(0, 0, 0, 0.4);
  border-radius: 5px;
  -webkit-transition: all 0.6s cubic-bezier(0.165, 0.84, 0.44, 1);
  transition: all 0.6s cubic-bezier(0.165, 0.84, 0.44, 1);
}

.box::after {
  content: "";
  border-radius: 5px;
  position: absolute;
  z-index: -1;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  box-shadow: 0 5px 15px rgba(0, 0, 0, 0.3);
  opacity: 0;
  -webkit-transition: all 0.6s cubic-bezier(0.165, 0.84, 0.44, 1);
  transition: all 0.6s cubic-bezier(0.165, 0.84, 0.44, 1);
}

.box:hover {
  -webkit-transform: scale(1.25, 1.25);
  transform: scale(1.25, 1.25);
  cursor: pointer;
}

.box:hover::after {
  opacity: 1;
}
```

demo地址：http://codepen.io/xiaokk06/pen/jrGapp

### 结语
&ensp;&ensp;主要采用scale方法是因为这个方法并不会引起重拍，而只引起元素的重绘。现代浏览器在完成以下四种属性的动画时，消耗的成本较低：position,scale,rotation和opacity。
